# Jurisdiction banding table
# FS = Financial Services banding, PC = Payments Compliance banding
# GC (Gambling Compliance) uses the same banding as FS (as no separate GC banding was provided)

BANDING: dict[str, dict] = {
    "Argentina":            {"fs": "1. High",   "pc": "1. High"},
    "Australia":            {"fs": "1. High",   "pc": "1. High"},
    "Austria":              {"fs": "1. High",   "pc": "1. High"},
    "Belgium":              {"fs": "1. High",   "pc": "1. High"},
    "Brazil":               {"fs": "1. High",   "pc": "1. High"},
    "Bulgaria":             {"fs": "1. High",   "pc": "1. High"},
    "California":           {"fs": "1. High",   "pc": "1. High"},
    "Chile":                {"fs": "1. High",   "pc": "1. High"},
    "Croatia":              {"fs": "1. High",   "pc": "1. High"},
    "Cyprus":               {"fs": "1. High",   "pc": "1. High"},
    "Czech Republic":       {"fs": "1. High",   "pc": "1. High"},
    "Denmark":              {"fs": "1. High",   "pc": "1. High"},
    "Estonia":              {"fs": "1. High",   "pc": "1. High"},
    "European Union":       {"fs": "1. High",   "pc": "1. High"},
    "Federal (Canada)":     {"fs": "1. High",   "pc": "1. High"},
    "Federal (US)":         {"fs": "1. High",   "pc": "1. High"},
    "Finland":              {"fs": "1. High",   "pc": "1. High"},
    "Florida":              {"fs": "1. High",   "pc": "1. High"},
    "France":               {"fs": "1. High",   "pc": "1. High"},
    "Germany":              {"fs": "1. High",   "pc": "1. High"},
    "Greece":               {"fs": "1. High",   "pc": "1. High"},
    "Hong Kong":            {"fs": "1. High",   "pc": "1. High"},
    "Hungary":              {"fs": "1. High",   "pc": "1. High"},
    "India":                {"fs": "1. High",   "pc": "1. High"},
    "Ireland":              {"fs": "1. High",   "pc": "1. High"},
    "Italy":                {"fs": "1. High",   "pc": "1. High"},
    "Japan":                {"fs": "2. Medium", "pc": "1. High"},
    "Latvia":               {"fs": "1. High",   "pc": "1. High"},
    "Lithuania":            {"fs": "1. High",   "pc": "1. High"},
    "Luxembourg":           {"fs": "1. High",   "pc": "1. High"},
    "Malta":                {"fs": "1. High",   "pc": "1. High"},
    "Massachusetts":        {"fs": "1. High",   "pc": "1. High"},
    "Netherlands":          {"fs": "1. High",   "pc": "1. High"},
    "New Jersey":           {"fs": "2. Medium", "pc": "1. High"},
    "New York":             {"fs": "1. High",   "pc": "1. High"},
    "New Zealand":          {"fs": "1. High",   "pc": "1. High"},
    "Norway":               {"fs": "1. High",   "pc": "1. High"},
    "Ontario":              {"fs": "1. High",   "pc": "1. High"},
    "Pennsylvania":         {"fs": "2. Medium", "pc": "1. High"},
    "Peru":                 {"fs": "2. Medium", "pc": "1. High"},
    "Poland":               {"fs": "1. High",   "pc": "1. High"},
    "Portugal":             {"fs": "1. High",   "pc": "1. High"},
    "Quebec":               {"fs": "2. Medium", "pc": "1. High"},
    "Romania":              {"fs": "1. High",   "pc": "1. High"},
    "Singapore":            {"fs": "1. High",   "pc": "1. High"},
    "Slovakia":             {"fs": "1. High",   "pc": "1. High"},
    "Slovenia":             {"fs": "1. High",   "pc": "1. High"},
    "South Korea":          {"fs": "2. Medium", "pc": "1. High"},
    "Spain":                {"fs": "1. High",   "pc": "1. High"},
    "Sweden":               {"fs": "1. High",   "pc": "1. High"},
    "Switzerland":          {"fs": "2. Medium", "pc": "1. High"},
    "United Kingdom":       {"fs": "1. High",   "pc": "1. High"},
    "Albania":              {"fs": "3. Low",     "pc": "2. Medium"},
    "China":                {"fs": "1. High",   "pc": "2. Medium"},
    "Colombia":             {"fs": "1. High",   "pc": "2. Medium"},
    "Costa Rica":           {"fs": "2. Medium", "pc": "2. Medium"},
    "Dominican Republic":   {"fs": "3. Low",    "pc": "2. Medium"},
    "Iceland":              {"fs": "1. High",   "pc": "2. Medium"},
    "Indonesia":            {"fs": "2. Medium", "pc": "2. Medium"},
    "Israel":               {"fs": "2. Medium", "pc": "2. Medium"},
    "Kenya":                {"fs": "2. Medium", "pc": "2. Medium"},
    "Liechtenstein":        {"fs": "2. Medium", "pc": "2. Medium"},
    "Malaysia":             {"fs": "2. Medium", "pc": "2. Medium"},
    "Mexico":               {"fs": "1. High",   "pc": "2. Medium"},
    "North Macedonia":      {"fs": "2. Medium", "pc": "2. Medium"},
    "Panama":               {"fs": "2. Medium", "pc": "2. Medium"},
    "Paraguay":             {"fs": "3. Low",    "pc": "2. Medium"},
    "Philippines":          {"fs": "2. Medium", "pc": "2. Medium"},
    "Puerto Rico":          {"fs": "3. Low",    "pc": "2. Medium"},
    "Qatar":                {"fs": None,         "pc": "2. Medium"},
    "Saudi Arabia":         {"fs": "2. Medium", "pc": "2. Medium"},
    "Serbia":               {"fs": "2. Medium", "pc": "2. Medium"},
    "South Africa":         {"fs": "1. High",   "pc": "2. Medium"},
    "Thailand":             {"fs": "2. Medium", "pc": "2. Medium"},
    "Turkey":               {"fs": "2. Medium", "pc": "2. Medium"},
    "United Arab Emirates, Federal": {"fs": "1. High", "pc": "2. Medium"},
    "United States, Arizona":     {"fs": "2. Medium", "pc": "2. Medium"},
    "United States, Colorado":    {"fs": "1. High",   "pc": "2. Medium"},
    "United States, Connecticut": {"fs": "2. Medium", "pc": "2. Medium"},
    "United States, Georgia":     {"fs": "1. High",   "pc": "2. Medium"},
    "United States, Illinois":    {"fs": "1. High",   "pc": "2. Medium"},
    "United States, Indiana":     {"fs": "3. Low",    "pc": "2. Medium"},
    "United States, Maryland":    {"fs": "2. Medium", "pc": "2. Medium"},
    "United States, Michigan":    {"fs": "2. Medium", "pc": "2. Medium"},
    "United States, Minnesota":   {"fs": "2. Medium", "pc": "2. Medium"},
    "United States, Nebraska":    {"fs": "3. Low",    "pc": "2. Medium"},
    "United States, North Carolina": {"fs": "1. High", "pc": "2. Medium"},
    "United States, Ohio":        {"fs": "2. Medium", "pc": "2. Medium"},
    "United States, Oregon":      {"fs": "2. Medium", "pc": "2. Medium"},
    "United States, Texas":       {"fs": "1. High",   "pc": "2. Medium"},
    "United States, Virginia":    {"fs": "2. Medium", "pc": "2. Medium"},
    "United States, Wisconsin":   {"fs": "3. Low",    "pc": "2. Medium"},
    "United States, Wyoming":     {"fs": "2. Medium", "pc": "2. Medium"},
    "Vietnam":              {"fs": "3. Low",    "pc": "2. Medium"},
    "Andorra":              {"fs": None,         "pc": "3. Low"},
    "Armenia":              {"fs": "3. Low",    "pc": "3. Low"},
    "Azerbaijan":           {"fs": None,         "pc": "3. Low"},
    "Bahrain":              {"fs": None,         "pc": "3. Low"},
    "Bangladesh":           {"fs": "3. Low",    "pc": "3. Low"},
    "Belarus":              {"fs": "3. Low",    "pc": "3. Low"},
    "Botswana":             {"fs": None,         "pc": "3. Low"},
    "Cambodia":             {"fs": None,         "pc": "3. Low"},
    "Egypt":                {"fs": "3. Low",    "pc": "3. Low"},
    "Georgia":              {"fs": "3. Low",    "pc": "3. Low"},
    "Ghana":                {"fs": "2. Medium", "pc": "3. Low"},
    "Jordan":               {"fs": "3. Low",    "pc": "3. Low"},
    "Kazakhstan":           {"fs": None,         "pc": "3. Low"},
    "Kuwait":               {"fs": None,         "pc": "3. Low"},
    "Kyrgyzstan":           {"fs": None,         "pc": "3. Low"},
    "Laos":                 {"fs": None,         "pc": "3. Low"},
    "Lebanon":              {"fs": None,         "pc": "3. Low"},
    "Mauritius":            {"fs": None,         "pc": "3. Low"},
    "Moldova":              {"fs": "3. Low",    "pc": "3. Low"},
    "Monaco":               {"fs": None,         "pc": "3. Low"},
    "Morocco":              {"fs": None,         "pc": "3. Low"},
    "Myanmar":              {"fs": None,         "pc": "3. Low"},
    "Namibia":              {"fs": "3. Low",    "pc": "3. Low"},
    "Nepal":                {"fs": "3. Low",    "pc": "3. Low"},
    "Nigeria":              {"fs": "2. Medium", "pc": "3. Low"},
    "Oman":                 {"fs": None,         "pc": "3. Low"},
    "Pakistan":             {"fs": "3. Low",    "pc": "3. Low"},
    "Sri Lanka":            {"fs": "3. Low",    "pc": "3. Low"},
    "Tajikistan":           {"fs": None,         "pc": "3. Low"},
    "Tunisia":              {"fs": None,         "pc": "3. Low"},
    "Turkmenistan":         {"fs": None,         "pc": "3. Low"},
    "Uganda":               {"fs": None,         "pc": "3. Low"},
    "United States, Alabama":     {"fs": "3. Low",    "pc": "3. Low"},
    "United States, Alaska":      {"fs": "2. Medium", "pc": "3. Low"},
    "United States, Arkansas":    {"fs": "3. Low",    "pc": "3. Low"},
    "United States, Delaware":    {"fs": "2. Medium", "pc": "3. Low"},
    "United States, Hawaii":      {"fs": "2. Medium", "pc": "3. Low"},
    "United States, Idaho":       {"fs": "3. Low",    "pc": "3. Low"},
    "United States, Iowa":        {"fs": "3. Low",    "pc": "3. Low"},
    "United States, Kansas":      {"fs": "2. Medium", "pc": "3. Low"},
    "United States, Kentucky":    {"fs": "3. Low",    "pc": "3. Low"},
    "United States, Louisiana":   {"fs": "3. Low",    "pc": "3. Low"},
    "United States, Maine":       {"fs": "3. Low",    "pc": "3. Low"},
    "United States, Mississippi":  {"fs": "3. Low",   "pc": "3. Low"},
    "United States, Missouri":    {"fs": "3. Low",    "pc": "3. Low"},
    "United States, Montana":     {"fs": "3. Low",    "pc": "3. Low"},
    "United States, Nevada":      {"fs": "3. Low",    "pc": "3. Low"},
    "United States, New Hampshire": {"fs": "3. Low",  "pc": "3. Low"},
    "United States, New Mexico":  {"fs": "3. Low",    "pc": "3. Low"},
    "United States, North Dakota": {"fs": "3. Low",   "pc": "3. Low"},
    "United States, Oklahoma":    {"fs": "3. Low",    "pc": "3. Low"},
    "United States, Rhode Island": {"fs": "3. Low",   "pc": "3. Low"},
    "United States, South Carolina": {"fs": "3. Low", "pc": "3. Low"},
    "United States, South Dakota": {"fs": "3. Low",   "pc": "3. Low"},
    "United States, Tennessee":   {"fs": "2. Medium", "pc": "3. Low"},
    "United States, Utah":        {"fs": "1. High",   "pc": "3. Low"},
    "United States, Vermont":     {"fs": "3. Low",    "pc": "3. Low"},
    "United States, Washington":  {"fs": "1. High",   "pc": "3. Low"},
    "United States, West Virginia": {"fs": "3. Low",  "pc": "3. Low"},
    "Uruguay":              {"fs": "2. Medium", "pc": "3. Low"},
    "Uzbekistan":           {"fs": "3. Low",    "pc": "3. Low"},
    "Zambia":               {"fs": None,         "pc": "3. Low"},
}

_LOWEST = "4. Lowest"

def get_banding(jurisdiction: str, area: str) -> str:
    """
    Return banding for a jurisdiction + compliance area.
    GC uses FS banding. Unknown jurisdictions → Lowest.
    """
    key = "fs" if area in ("Financial Services", "Gambling Compliance") else "pc"
    entry = BANDING.get(jurisdiction)
    if entry is None:
        return _LOWEST
    val = entry.get(key)
    return val if val is not None else _LOWEST


BANDING_ORDER = {"1. High": 0, "2. Medium": 1, "3. Low": 2, "4. Lowest": 3}
BANDING_COLOURS = {
    "1. High":   "#d62728",
    "2. Medium": "#ff7f0e",
    "3. Low":    "#2ca02c",
    "4. Lowest": "#aec7e8",
}
